### PR TITLE
Adjust quanta to quantum and quantas to quanta

### PR DESCRIPTION
**Pull request by JulianLeviston**
This adjusts Quanta to Quantum as the singular, and Quantas to Quanta as the plural.

### CODE REVIEW

**Comment by mordrax** [comment]
What, two minutes in and you're already making PRs! imo, the name for that record doesn't describe what it is at all! I'd rather pick another name that describes what it is rather than pick on the plurality of it.

**Comment by JulianLeviston** [comment]
@mordrax I think it's a pretty good name. `a required or allowed amount`. I suppose you *could* call it an `Event` if you wanted ;-) WDYT? call for other names? @martinstannard

**Comment by JulianLeviston** [comment]
@mordrax so should I just close this?

**Comment by mordrax** [comment]
I'm happy to merge it because it's correct.

However, i was thinking, not too far down the line, we're going to move the decoder into it's own module and it'll spit out stuff like `MathProgress` or `ReadingHistory` and the like. So not too fussed what it's called atm.

**Comment by JulianLeviston** [comment]
So... 🚢 ?

**Comment by mordrax** [comment]
:sheep:

**Comment by JulianLeviston** [comment]
Closing because changes already used in https://github.com/blake-education/eventful/pull/3

**Pull request closed without merging**
