### PR TITLE
Feature/add basic loading status

### PR DESCRIPTION
**Pull request by JulianLeviston**
This adds a basic loading status to the "Get History" button when the app is loading data from the backend.

Also adds a changelog, and puts .DS_Store files into the .gitignore file.

### CODE REVIEW

**Comment by mordrax** [comment]
I think isLoading should be tied in with model.quanta in such a way that we only represent possible states, i.e it's impossible to be both loading and have the loaded quanta (if someone forgets to turn isLoading off or if there's some race condition with the Tasks).
```
type PageData a = Loading (Maybe a) | Data a

type alias Model = {
    data : PageData Quanta
```

So in this way, we list all possible states of the page data in one type.

**Comment by mordrax** [comment]
Just like to add:

This is from a pov of 'making impossible states impossible'. Consider the following case
```
model = 
{ quanta = [ Quantum, Quantum ]
, isLoading = true
, flashMsg = "The data failed to load" -- hypothetical next PR to display FetchFail msgs
}
```

Which is correct? It's impossible to tell.

`type PageData = Loading | Data a | Failed FlashMsg`

This makes it easy to understand the state we are in and impossible to represent any other artificial states.

**Comment by mordrax** [comment]
I just had another look and I think I need to stop worrying too much about getting it 'too' right as the code is still evolving and having open PRs that take a long time to get merged will also sap momentum and motivation.

There is nothing wrong with this PR! :ship: :ship: :ship:

**Comment by JulianLeviston** [comment]
Yeah, there are some better names, probably, but we can adjust in time pretty easily :) 👍 thanks.

**Pull request merged**
